### ISSUE TITLE
Can't access logout link when owing money

### ISSUE THREAD

**Issue by nfilzi** [guillaumecabanel/seazon_at_dojo#6]
![screen shot 2018-08-27 at 22 28 31](https://user-images.githubusercontent.com/7533706/44684143-8e813600-aa48-11e8-8736-5864e1b27859.png)

**Comment by nfilzi** [comment]
The yellow reminder hides the logout link

**Comment by guillaumecabanel** [comment]
good catch, can you confirm that is admin specific on your screen?

**Comment by nfilzi** [comment]
Well, I'm indeed seeing it as an admin.

**Comment by nfilzi** [comment]
![screen shot 2018-08-28 at 09 29 59](https://user-images.githubusercontent.com/7533706/44707490-f2394c80-aaa4-11e8-86cc-78b2c142db4d.png)
Don't have the bug as a regular user indeed!

**Comment by guillaumecabanel** [comment]
What do you think about these solutions:
1. Add a dropdown for admin actions (worsen UX)
2. Don't show payment warning for admin (she's the one who get the money after all)
3. Something else

**Comment by nfilzi** [comment]
I'd go at it maybe differently: keep the warning in the navbar, to make it visible at all time. But make it a link to an explanation page, that could become later, when we'll get the time to do it, a Pay with Lydia page. What do you think?

**Comment by nfilzi** [comment]
I know Tim implemented it in of his app, it works nicely!

**Comment by guillaumecabanel** [comment]
something like this?
"À payer 7€ ℹ"
