### ISSUE TITLE
Allow users to specify need for expenses report

### ISSUE THREAD

**Issue by nfilzi** [guillaumecabanel/seazon_at_dojo#8]
Like an account preference or sth like that.

It'll allow us to compute the amount owned automatically.
And it'll allow us to generate automatic expenses reports later on.

**Comment by guillaumecabanel** [comment]
how we should handle passed orders? I think we need an attribute by order and a preference by user. What do you think?

**Comment by nfilzi** [comment]
When you talk about past orders, you mean the ones which, in any case, won't be eligible to be expense reports?

Otherwise:
User preference: definitely, it'll be the one we use by default on any order from a user
Order preference: could be useful, if we want to enable users to override their default on a per-order basis.

**Comment by nfilzi** [comment]
Not sure all of them are. The first ones were definitely not.

On an other hand, the ideal situation would be to get the past data in the app (as much as possible), and then offer people to review these past orders and indicate if they need it to be eligible for an expense report.
We would have to compile all the past data out of the simple polls on Slack, and double check with Mariette that these were paid correctly.

Another (simpler) solution would be to just ignore the old orders that are not in the system yet, and carry on from there.

What do you think?

**Comment by guillaumecabanel** [comment]
Do we need a user preference? If we have a column for orders to say if the price should or should not include +5.5%, could we just assume a default choice from the last order?

**Comment by guillaumecabanel** [comment]
yes we need it to be explicit on displayed prices :)

**Comment by guillaumecabanel** [comment]
done in 33eba975e5e1abd953cf4b07bf816919b9ccf8b0
